### ISSUE TITLE
New project talk

### ISSUE THREAD

**Issue by abmusse** [IBM/ibmi-db2util#1]
**[Original report](https://bitbucket.org/litmis/db2util/issue/1) by Aaron Bartell (Bitbucket: [aaronbartell](https://bitbucket.org/aaronbartell), GitHub: [aaronbartell](https://github.com/aaronbartell)).**

----------------------------------------

This conversation originally started in the [this ibmichroot thread](https://bitbucket.org/litmis/ibmichroot/issues/38) and is being moved here for context relevance purposes.

@rangercairns, reminder that bitbucket doesn't default notification of new issues so [make sure to set them](http://www.screencast.com/t/varSPiim).

**Comment by ThePrez** [comment]
Since this has been "rotting on the vine" and there is no established business need for some of the outstanding issues, I am closing this issue.
