### ISSUE TITLE
Error occurred in SQL Call Level Interface SQLSTATE=HY009 SQLCODE=-99999 on V7R3 but not V7R4

### ISSUE THREAD

**Issue by richardschoen** [IBM/ibmi-db2util#20]
The following query can reproduce the error: 
```/QOpenSys/pkgs/bin/db2util -o json "select * from QSYS2.SYSCOLUMNS where TABLE_SCHEMA = 'QIWS'"```

The same SQL query works in ACS Run SQL on both V7R3 and V7R4.
```select * from QSYS2.SYSCOLUMNS where TABLE_SCHEMA = 'QIWS'"```

Could there be some sort of data casting issue that occurs on V7R3 but not V7R4 ?

Using db2util V1.0.12

**Comment by richardschoen** [comment]
Looks like the COLUMN_EXPRESSION field which is a large clob might be the culprit. 

```/QOpenSys/pkgs/bin/db2util "select COLUMN_EXPRESSION from QSYS2.SYSCOLUMNS where TABLE_SCHEMA = 'QIWS'"```

Causes the error on V7R3, but not V7R4.

**Comment by worksofliam** [comment]
@richardschoen thanks for the research. I will wait for that issue to be fixed.

**Comment by richardschoen** [comment]
Appears to be a TR issues with DB2 on V7R3.

**Comment by richardschoen** [comment]
Appears to be a TR issues with DB2 on V7R3.

**Comment by kadler** [comment]
CLI doesn't allow binding to SQL_CHAR > 32767 for some dumb reason. I put out a PTF that ~~ignores values larger and treats them as 32767, but that still doesn't help if the value is bigger than that (eg. in a CLOB). We'd need to add special code to bind LOBs in that case.~~ removes the length restriction for SQL_C_CHAR. We could work around the issue for now by capping the buffer size at 32767 or bind as SQL_CLOB when lengths > 32767.

**Comment by kadler** [comment]
FYI: PTFs are SI69780 for 7.2, SI69779 for 7.3, and SI69778 for 7.4. Forget what I said about treating them as 32767, the change I made removes the limitation.

**Comment by richardschoen** [comment]
@worksofliam Probably want to add this to your docs for database browser.
