### ISSUE TITLE
Compile db2util on Linux

### ISSUE THREAD

**Issue by abmusse** [IBM/ibmi-db2util#4]
**[Original report](https://bitbucket.org/litmis/db2util/issue/4) by Anonymous.**

----------------------------------------

This might be massively out of scope of this project.

My research has shown that there is no easy or practical way to use some of the nice new features of our beloved IBM i from the outside, lets say from a Linux machine. Lets say you wanted to leverage some of the new QSYS2 functions to do in depth monitoring of an IBM i box from one of the Open Source monitoring solutions. There seems to be no way of doing this.

This tool running on a Linux machine would be exactly what is needed.

PS: I know that it is possible to create services on the IBM i with node oder python to get access to those functions, but what is needed is not yet another process or server but instead use the basic system functionality.

**Comment by ThePrez** [comment]
The need to remove ODBC as a requirement expands this proposal far beyond the scope of db2util. Closing for that reason (feel free to reopen if a business need remains)
